angular.module('qui.constant', [])
  .constant('CURRENCY', {
    USD: 'USD United States Dollars',
    EUR: 'EUR Euro',
    CAD: 'CAD Canada Dollars',
    GBP: 'GBP United Kingdom Pounds',
    DEM: 'DEM Germany Deutsche Marks',
    FRF: 'FRF France Francs',
    JPY: 'JPY Japan Yen',
    NLG: 'NLG Netherlands Guilders',
    ITL: 'ITL Italy Lira',
    CHF: 'CHF Switzerland Francs',
    DZD: 'DZD Algeria Dinars',
    ARP: 'ARP Argentina Pesos',
    AUD: 'AUD Australia Dollars',
    ATS: 'ATS Austria Schillings',
    BSD: 'BSD Bahamas Dollars',
    BBD: 'BBD Barbados Dollars',
    BEF: 'BEF Belgium Francs',
    BMD: 'BMD Bermuda Dollars',
    BRR: 'BRR Brazil Real',
    BGL: 'BGL Bulgaria Lev',
    CLP: 'CLP Chile Pesos',
    CNY: 'CNY China Yuan Renmimbi',
    CYP: 'CYP Cyprus Pounds',
    CSK: 'CSK Czech Republic Koruna',
    DKK: 'DKK Denmark Kroner',
    XCD: 'XCD Eastern Caribbean Dollars',
    EGP: 'EGP Egypt Pounds',
    FJD: 'FJD Fiji Dollars',
    FIM: 'FIM Finland Markka',
    XAU: 'XAU Gold Ounces',
    GRD: 'GRD Greece Drachmas',
    HKD: 'HKD Hong Kong Dollars',
    HUF: 'HUF Hungary Forint',
    ISK: 'ISK Iceland Krona',
    IDR: 'IDR Indonesia Rupiah',
    IEP: 'IEP Ireland Punt',
    ILS: 'ILS Israel New Shekels',
    JMD: 'JMD Jamaica Dollars',
    JOD: 'JOD Jordan Dinar',
    LBP: 'LBP Lebanon Pounds',
    LUF: 'LUF Luxembourg Francs',
    MYR: 'MYR Malaysia Ringgit',
    MXP: 'MXP Mexico Pesos',
    NZD: 'NZD New Zealand Dollars',
    NOK: 'NOK Norway Kroner',
    PKR: 'PKR Pakistan Rupees',
    XPD: 'XPD Palladium Ounces',
    PHP: 'Philippines Pesos',
    XPT: 'XPT Platinum Ounces',
    PLZ: 'PLZ Poland Zloty',
    PTE: 'PTE Portugal Escudo',
    ROL: 'ROL Romania Leu',
    RUR: 'RUR Russia Rubles',
    SAR: 'SAR Saudi Arabia Riyal',
    XAG: 'XAG Silver Ounces',
    SGD: 'SGD Singapore Dollars',
    SKK: 'SKK Slovakia Koruna',
    ZAR: 'ZAR South Africa Rand',
    KRW: 'KRW South Korea Won',
    ESP: 'ESP Spain Pesetas',
    XDR: 'XDR Special Drawing Right (IMF)',
    SDD: 'SDD Sudan Dinar',
    SEK: 'SEK Sweden Krona',
    TWD: 'TWD Taiwan Dollars',
    THB: 'THB Thailand Baht',
    TTD: 'TTD Trinidad and Tobago Dollars',
    TRL: 'TRL Turkey Lira',
    VEB: 'VEB Venezuela Bolivar',
    ZMK: 'ZMK Zambia Kwacha',
  });
